### ISSUE TITLE
Documentação de Contexto > Justificativa

### ISSUE THREAD

**Issue by rodrigojgrande** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-mafia_do_zap#10]

**Comment by enricoarj** [comment]
Atualizei a justificativa, mas aceito sugestões para melhorar.

**Comment by Nicole-Castro** [comment]
links de notícias com dados

https://g1.globo.com/jornal-hoje/noticia/2023/05/03/pesquisa-revela-que-43percent-dos-jovens-nao-sabem-checar-se-uma-informacao-da-internet-e-falsa.ghtml

https://www.estadao.com.br/estadao-verifica/idosos-compartilham-sete-vezes-mais-noticias-falsas-do-que-usuarios-mais-jovens-no-facebook-diz-pesquisa/

https://www.bbc.com/portuguese/brasil-46849533

https://www2.ufjf.br/noticias/2023/06/30/midias-sociais-e-jornalismo-os-perigos-da-desinformacao/
