### ISSUE TITLE
Referências bibliográfica > Referências

### ISSUE THREAD

**Issue by rodrigojgrande** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-mafia_do_zap#16]

**Comment by enricoarj** [comment]
Idosos são mais propensos a espalhar notícias falsas, diz estudo. Disponível em: <https://www.bbc.com/portuguese/brasil-46849533>. Acesso em: 12 mar. 2024. 
Mídias sociais e jornalismo: os perigos da desinformação. Disponível em: <https://www2.ufjf.br/noticias/2023/06/30/midias-sociais-e-jornalismo-os-perigos-da-desinformacao/>. Acesso em: 12 mar. 2024. 
MONNERAT, A. Idosos compartilham sete vezes mais notícias falsas do que jovens no Facebook, diz pesquisa. Disponível em: <https://www.estadao.com.br/estadao-verifica/idosos-compartilham-sete-vezes-mais-noticias-falsas-do-que-usuarios-mais-jovens-no-facebook-diz-pesquisa/>. Acesso em: 12 mar. 2024. 
Pesquisa revela que 43% dos jovens não sabem checar se uma informação da internet é falsa. Disponível em: <https://g1.globo.com/jornal-hoje/noticia/2023/05/03/pesquisa-revela-que-43percent-dos-jovens-nao-sabem-checar-se-uma-informacao-da-internet-e-falsa.ghtml>. Acesso em: 12 mar. 2024.
