### ISSUE TITLE
Artefatos da Sprint 1 > Slides

### ISSUE THREAD

**Issue by Nicole-Castro** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-mafia_do_zap#24]

**Comment by rodrigojgrande** [comment]
Link da apresentação: [Link](https://sgapucminasbr-my.sharepoint.com/:p:/g/personal/1494305_sga_pucminas_br/ET-80rjaa1dEmLluwHQXn7sB5O4D1A_AbwqG4sc9CO_mwQ?e=DmTPUc)
